### ISSUE TITLE
fastobo-validator fails with Killed: 9

### ISSUE THREAD

**Issue by beckyjackson** [fastobo/fastobo-validator#48]
Hi there! We are using the `fastobo-validator` as part of the Human Disease Ontology release process.

We went to make the release yesterday and ran into this new error:
```
curl -Lk -o build/fastobo.tar.gz https://bintray.com/fastobo/fastobo-validator/download_file?file_path=stable%2Ffastobo_validator-x86_64-apple-darwin.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  611k  100  611k    0     0   338k      0  0:00:01  0:00:01 --:--:-- 1647k
cd build && tar -xvf fastobo.tar.gz
x README.md
x CHANGELOG.md
x COPYING
x fastobo-validator
build/fastobo-validator src/ontology/doid.obo 
make: *** [validate-src/ontology/doid] Killed: 9
```

We've been using this for the better part of this year and haven't ever seen the process killed like this. I can still run it successfully on my machine, which is running macOS v10.14.6, but @lschriml ran into the error above running it on macOS v11.0.1 (she updated last week, so it's the most recent change). The `fastobo-validator` file is still dated Feb 13, 2020, so that leads me to think that the error is caused by the newer operating system.

Any thoughts on how to resolve this? It would be immensely helpful if we could get more details in the error message, but I'm not familiar enough with Rust to see where this error could be coming from. Thanks so much!

**Comment by althonos** [comment]
Hi !

I traced the error back to Bintray, which is not letting me update releases more than 1 year old. I was planning to use a release named `stable` which I could update incrementally, but unfortunately this means I can't do that, and my builds have been starting to fail deployment recently because of this. So basically, you're not getting the latest stable version when downloading with the `stable` URL. 

Could you try again with the versioned URL that resolves to the latest version: https://bintray.com/fastobo/fastobo-validator/download_file?file_path=v0.4.0%2Ffastobo_validator-x86_64-apple-darwin.tar.gz ?

> Any thoughts on how to resolve this? It would be immensely helpful if we could get more details in the error message, but I'm not familiar enough with Rust to see where this error could be coming from. Thanks so much!

The thing is, normally Rust has a nice backtrace when the error is a recoverable error, but here the `SIGKILL` is probably coming from the OS, which means there is no way to know more about this...

**Comment by beckyjackson** [comment]
Thanks so much for looking into this! That new version works perfectly with macOS 11.0.1.

I'll keep a lookout for the new releases on Bintray 🙂

**Comment by althonos** [comment]
You can watch this repository for releases only on GitHub, and that will warn you when I make a new release (which is not that often) :wink: In the meantime, I have updated the links in the README so that they don't point to the outdated version.
